### ISSUE TITLE
Updating scale of physics bodies

### ISSUE THREAD

**Issue by wmurphyrd** [donmccurdy/aframe-physics-system#10]
Is there an efficient way to update the size of physics bodies to match changes to entity `scale`? It can be accomplished via `removeBody` and `initBody`, but this seems to have a cumulative impact on performance.

**Comment by donmccurdy** [comment]
I don't know of anything I'd consider particularly efficient, but you could improve on re-creating the component. Instead of that (which would re-instantiate the component, CANNON.Body, and CANNON.Shape instances, you can probably just replace the CANNON.Body's shape.

```js
var mesh2shape = require('three-to-cannon');

// Remove existing shapes.
el.body.shapes.length = 0;
el.body.shapeOffsets.length = 0;
el.body.shapeOrientations.length = 0;
el.body.addShape( mesh2shape( mesh ) );
```

Options for [three-to-cannon documented here](https://github.com/donmccurdy/three-to-cannon).

If you know the shape will always be a box, you could probably just modify shape.halfExtents and some other shape properties. But there's no performant way to handle every possible situation, given other performance-based decisions in the CANNON.js API, so I don't think this can be handled by the A-Frame physics system itself.

**Comment by wmurphyrd** [comment]
Thanks!
