### ISSUE TITLE
AmmoJS Driver

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/aframe-physics-system#116]
@InfiniteLee reading through your branch (https://github.com/donmccurdy/aframe-physics-system/compare/master...InfiniteLee:feature/ammo_driver) and leaving some comments and questions here. 

1. What's the full (minified and/or gzipped) size of AmmoJS? I think that may determine the value keeping CannonJS support.
2. In `ammo-driver.js`, the exports are defined inside of a promise `.then()` callback. I can't see why that would be necessary... maybe have the driver `init()` method return a promise, instead? Or is there another issue I've missed?
3. Do you expect to keep using CannonJS for anything, or move entirely to AmmoJS? Any early comparison takeaways?
4. How does `debugDrawMode` work? Does that let us implement drawing in three.js, or does AmmoJS use the GL context itself?

**Comment by InfiniteLee** [comment]
hey @donmccurdy - sorry been out of town for the past couple of weeks so haven't been working on this stuff. But I'm back now. 

1. The current `ammo.js` builds are here: https://github.com/kripken/ammo.js/tree/master/builds and you can see the sizes of the wasm and asm builds. It looks like the recent version of emscripten has brought both versions to about the same size of eachother, 1.6-1.7 MB. That said, the actual size we use for `aframe-physics-system` might be smaller, as it's possible to remove unused bindings from ammo and recompile to make the builds smaller (https://github.com/kripken/ammo.js#reducing-build-size). It also might be bigger if we decide there's more features we want to expose from bullet or not. 

2. No, this is probably just my lack of experience in js showing (and me just trying to do the fastest thing possible). I'll try having the `init()` return a promise and see how that goes.

3. Assuming we're ok with the size of the ammo.js build, its probably ok just to switch over assuming I can get feature parity. The last thing I was having issues with was getting constraints to work in Ammo the same way they work for Cannon (necessary for `aframe-super-hands-component` to work correctly), and that's been tricky.

4. Bullet/Ammo only provides a virtual interface for debug drawing with a handful of methods which it expects to be implemented on the game engine side. I've done this with three.js via https://github.com/InfiniteLee/ammo-debug-drawer. If one wanted a pure GL implementation, they could implement their own debug-drawer similar to the one I made, but using gl calls instead of three.js ones. (considered doing that, but I wasn't sure how to resolve doing direct gl stuff at the same time as having something like three doing it's own gl calls simultaneously, so keeping everything in three made it simple, especially if you wanted to support rendering depth/order).

**Comment by donmccurdy** [comment]
Added by @InfiniteLee in #125.

Thanks again @InfiniteLee, excited to make this available for more A-Frame users! :)
