### ISSUE TITLE
TypeError: Cannot read property 'computeBoundingSphere' of null at createBoundingSphereShape 

### ISSUE THREAD

**Issue by micahstubbs** [donmccurdy/aframe-physics-system#15]
[demo to reproduce issue](http://bl.ocks.org/micahstubbs/94e06c2849b6c7c60105d0243bc1936a)

this stackoverflow answer [In a port from Three.js 68 to 69: Cannot read property 'boundingSphere' of undefined](http://stackoverflow.com/questions/26724715/in-a-port-from-three-js-68-to-69-cannot-read-property-boundingsphere-of-undef) looks related  

![screen shot 2017-01-13 at 6 18 55 am](https://cloud.githubusercontent.com/assets/2119400/21933013/5f36ab54-d958-11e6-9eb3-1cf2c4f25a05.png)

**Comment by wmurphyrd** [comment]
I've seen this one, too. Started with the controller refactor in Aframe v.0.4.0, `tracked-controls` is no longer added to the entity when `vive-controls` is initiated; instead it is added when the controller is detected.  `mesh2shape()` assumes there is an object3d and fails when trying to call its computeBoundingSphere method. 

[Here is the workaround I've been using](https://github.com/wmurphyrd/aframe-super-hands-component/blob/master/examples/physics/index.html#L17).

It is also not currently possible to add a `static-body` to `hand-controls` because of a similar issue of assuming a mesh exists. 

One solution would be for initBody to check if a manual shape is fully specified (as in "shape: sphere; sphereRadius: 0.02;") and skip the mesh2shape call.

**Comment by micahstubbs** [comment]
@donmccurdy curious, is there a fix for this issue? did we fail to provide enough info to reproduce it?

**Comment by micahstubbs** [comment]
maybe @Datatitian's workaround is the suggested solution 🤔

**Comment by wmurphyrd** [comment]
@micahstubbs [update in three-to-cannon](https://github.com/donmccurdy/three-to-cannon/commit/07129dcf6ac77fb205b71b34126ed206e5f2d349) looks like a fix for when you specify sphereRadius, and a graceful failure in other cases

**Comment by donmccurdy** [comment]
@micahstubbs I only just now updated the version of aframe-extras to use the new three-to-cannon, so if you were getting physics through that repo it should be fixed now
