### ISSUE TITLE
Support physics in a Web Worker

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/aframe-physics-system#16]
Ok so, the plan.

Body and World objects will be replaced with stubs or [proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy). Modifications to either are recorded and sent (batched) to a remote driver. The driver pushes back, asynchronously, data about the state of all current bodies, and intersections.

## Client operations:

- body.applyImpulse()
- body.applyForce()
- world.add/removeConstraint()
- world.add/removeBody()

Most/all property modifications should also be persisted.

## Drivers:

- LocalPhysicsDriver.js
- WorkerPhysicsDriver.js
- Client / ServerPhysicsDriver.js *(someday)*

## Serialization:

Driver will, at each tick, provide a description of scene state. Rough sketch:

```
{
  type: 'step',
  bodies: [ ... array of object IDs, lengths ],
  collisions: [ ... ? ... ],
  data: [ ... arraybuffer of positions/velocities/angularVelocities ... ]
}
```

Data, as an arraybuffer, may be passed back to avoid copying data. This might be a very premature optimization.

## Distributed files:

- aframe-physics-system.full.js (aframe lib + local driver)
- aframe-physics-system.js + worker-physics-driver.js
- aframe-physics-system.js + client-physics-driver.js / server-physics-driver.js

## Open questions:

- [ ] Serializing *state* of a Cannon.Body isn't hard, but serializing the initialization data (shapes, potentially nested) kind of seems painful. Can users still call `addBody` themselves? What's the most precise way to represent geometry?
- [ ] How to make collisions (events, or just the list) available to the aframe client?

**Comment by donmccurdy** [comment]
## Expected breaking changes

- remove physics from aframe-extras, or deliver only local driver
- remove support for kinematic-body
- default shape to box, not trimesh

**Comment by wmurphyrd** [comment]
This is going to be great for performance! 

Regarding collisions, `physics-collider` [loops through the world contact equations and used references to the collider's body object and the other bodies' references to their elements](https://github.com/wmurphyrd/aframe-physics-system/blob/interfaces/src/components/interfaces/aframe-physics-collider.js#L33-L40). Since we'll no longer have access to body references from the scene nor entity references from the physics worker, perhaps return a map of colliding object IDs


```js
// in the physics worker
var collisions = {};
world.contacts.forEach( contact => {
  let bodID1 = bodyToIDWeakMap.get(contact.bi), // a WeakMap global in the service worker
    bodID2 = bodyToIDWeakMap.get(contact.bj);
  collisions[bodID1] = collisions[bodID1] ? collisions[bodID1].push(bodID2)  :  [bodID2];
  collisions[bodID2] = collisions[bodID2] ? collisions[bodID2].push(bodID1)  :  [bodID1];
});

// and in client components
var collisions = this.el.sceneEl.systems.physics.data.state.collisions,
  IDMap = this.el.sceneEl.systems.physics.IDToEntityMap;
var myCollidedEntities = collisions[IDMap.get(this.physicsBodyID)].map(IDMap.get);
```

My wishlist for the API would be some way to [update the physics body shapes for changes in scale](https://github.com/wmurphyrd/aframe-super-hands-component/blob/master/reaction_components/stretchable.js#L34-L37) from `super-hands` `stretchable`
