### ISSUE TITLE
Update not called on physics system when changed.

### ISSUE THREAD

**Issue by AdaRoseEdwards** [donmccurdy/aframe-physics-system#21]
The `physics` is a system. Which unfortunately does not fire update when it is changed. 

https://aframe.io/docs/0.5.0/core/systems.html

It would be great if it was a component instead so that it could be updated dynamically.

**Comment by donmccurdy** [comment]
Yeah, it's been an issue. The helpful thing about systems is that they're guaranteed to `init()` first and `tick()` last, which i'm taking advantage of. I'm hoping https://github.com/aframevr/aframe/issues/2071 will be fixed in 0.6.0, in which case systems will have the same update support as components.

**Comment by donmccurdy** [comment]
Closing this here but 0.6.0 milestones should have it covered: https://github.com/aframevr/aframe/milestone/5
