### ISSUE TITLE
Player colision with wavefront(obj)

### ISSUE THREAD

**Issue by DavidGonzalezGutierrez** [donmccurdy/aframe-physics-system#30]
I have implanted a mapping with multiple walls in obj. But in no way do I get any collisions detected. Does it work in obj with multiple vertices?

**Comment by donmccurdy** [comment]
Arbitrary meshes are not well-supported by cannonjs (or native physics engines, for that matter).

The best options for walls would be:

1) If you have models for each wall, you can wrap them with a bounding box via `static-body="shape: box"`.
2) If you have one large model for the whole scene, you can use the aframe-inspector to position invisible boxes where the walls are, and add a static body to each. For example: `<a-box width="5" visible="false" static-body></a-box>

There's more detail in #9, so I'm going to close the issue here.

**Comment by DavidGonzalezGutierrez** [comment]
I thought so, but I preferred to ask. Thanks for your time.
