### ISSUE TITLE
Collisions -- how do I tell what faces of each colliding body intersected?

### ISSUE THREAD

**Issue by aas395** [donmccurdy/aframe-physics-system#43]
Hi,

I've created a static-body entity and set up an event handler to let me know when the player collides with it. I'm trying to find out which face of the body the player collided with, so I logged `event.detail` for the collision event, but it wasn't clear to me that that information was anywhere in the `detail` property. I checked `event.detail.contact`, and nothing stood out to me as anything that would represent the face of the body where the two objects intersected.

I'm new to aframe, so it's possible I missed this.

Thank you for all your awesome work!

**Comment by donmccurdy** [comment]
I don't think the physics engine can tell you which faces collided; generally you'll be approximating the faces of the actual mesh anyway, using geometric shapes or a convex hull, to keep the simulation fast. What Cannon.js _does_ provide is info about the world coordinates of the collision:

https://github.com/schteppe/cannon.js/issues/118#issuecomment-33205873

I don't have an example to offer, but you should be able to raycast from the object's center out toward the collision point and [THREE.Raycaster](https://threejs.org/docs/#api/core/Raycaster) will tell you which face was intersected. This does assume your mesh is convex-ish, otherwise you'll need to get creative.

**Comment by aas395** [comment]
Thank you for looking into this for me. I'll look into the Raycasting idea as I continue to experiment.

Thanks again for all your awesome work!
